### ISSUE TITLE
[MODULE] Store the score of a tournament in the Blockchain

### ISSUE THREAD

**Issue by 0xEDU** [0xEDU/ft_transcendence#10]
- [x] Blockchain Integration: The primary goal of this module is to seamlessly integrate blockchain technology, specifically Ethereum , into the Pong website. This integration ensures the secure and immutable storage of tournament scores, providing players with a transparent and tamper-proof record of their gaming achievements.
- [x] Solidity Smart Contracts: To interact with the blockchain, we will develop Solidity smart contracts. These contracts will be responsible for recording, managing, and retrieving tournament scores.
- [x] Testing Blockchain: As mentioned earlier, a testing blockchain will be employed for development and testing purposes. This ensures that all blockchainrelated functionalities are thoroughly validated without any risks associated with a live blockchain.
- [x] Interoperability: This module may have dependencies on other modules, particularly the Backend Framework module. Integrating blockchain functionality might necessitate adjustments in the backend to accommodate interactions with the blockchain.

**Comment by rodsmade** [comment]
~@0xEDU Tudo certo com essa issue? Pode fechar? Ou vale a pena detalhar itens q ainda faltam implementar usando checklist?~
- [ ] ~tipo assim~
- [x] ~e assim~
- [ ] ~etc.~

Edit:
Copiei os bulletpoints do pdf na descrição dessa issue, pfvr dá uma olhada Edu e marca o que já tá OK, pra gente acompanhar o andamento
