### ISSUE TITLE
Achievements (model, view, imagens)

### ISSUE THREAD

**Issue by rodsmade** [0xEDU/ft_transcendence#42]
- [x] List of achievements with milestones
- [x] Achievements icons
- [x] Achievements table
- [x] Achievements being dynamically displayed in user's profile (Django View)

**Comment by ferfahl** [comment]
Actually the table will be the table from user stats, that way we can just check the user stats and give the reply with the image chosen

**Comment by ferfahl** [comment]
- [x] hoovering mouse on top of the achievement gives it's name and a message
- [x] table of achievements being created with the user table
- [x] table of achievements starting all values with 0
