### ISSUE TITLE
[UX enhancement] Stats/Matches History: behaviour for empty co-op/classic matches

### ISSUE THREAD

**Issue by rodsmade** [0xEDU/ft_transcendence#58]
Currently there's no clear indication to the user that the empty spaces will be eventually filled with statistics, as there is for the matches cards

![image](https://github.com/0xEDU/ft_transcendence/assets/49699403/3719e9ed-ef13-4359-b1c1-b6048e85560a)

**Comment by ferfahl** [comment]
![Image](https://github.com/0xEDU/ft_transcendence/assets/102756887/97bd7a34-118c-494c-bff1-caba912c1196)
